---
apiVersion: v1
kind: Secret
metadata:
  name: webhooks-https-certs
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "webhooks")) | nindent 2 }}
type: kubernetes.io/tls
data:
  ca.crt: {{ .Values.sdsDrbd.internal.customWebhookCert.ca }}
  tls.crt: {{ .Values.sdsDrbd.internal.customWebhookCert.crt }}
  tls.key: {{ .Values.sdsDrbd.internal.customWebhookCert.key }}
