apiVersion: v1
kind: ServiceAccount
metadata:
  name: sds-drbd-operator
  namespace: d8-linstor
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: d8:linstor:sds-drbd-operator
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
      - patch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - list
  - apiGroups:
      - storage.deckhouse.io
    resources:
      - blockdevices
      - lvmchangerequests
      - linstorstorageclasses
      - linstorstoragepools
      - lvmvolumegroups
      - drbdoperatorstoragepools
    verbs:
      - get
      - list
      - create
      - delete
      - watch
      - update
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - create
      - delete
      - list
      - get
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: d8:linstor:sds-drbd-operator
subjects:
  - kind: ServiceAccount
    name: sds-drbd-operator
    namespace: d8-linstor
roleRef:
  kind: ClusterRole
  name: d8:linstor:sds-drbd-operator
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: d8:linstor:sds-drbd-operator
  namespace: d8-linstor
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: d8:linstor:sds-drbd-operator
  namespace: d8-linstor
subjects:
  - kind: ServiceAccount
    name: sds-drbd-operator
    namespace: d8-linstor
roleRef:
  kind: Role
  name: d8:linstor:sds-drbd-operator
  apiGroup: rbac.authorization.k8s.io
