apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: drbdstoragepools.storage.deckhouse.io
  labels:
    heritage: deckhouse
    module: storage
spec:
  group: storage.deckhouse.io
  scope: Cluster
  names:
    plural: drbdstoragepools
    singular: drbdstoragepool
    kind: DRBDStoragePool
    shortNames:
      - drbdsp
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          description: "drbd storage pool"
          properties:
            spec:
              type: object
              properties:
                type:
                  type: string
                  enum: [ 'LVM','LVMThin' ]
                lvmvolumegroups:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      thinpoolname:
                        type: string
            status:
              type: object
              properties:
                phase:
                  type: string
                  enum: [ 'Updating','Failed', 'Completed' ]
                reason:
                  type: string
