{{- if .Values.sdsDrbd.internal.masterPassphrase }}
apiVersion: v1
kind: Secret
metadata:
  name: linstor-passphrase
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list .) | nindent 2 }}
type: Opaque
data:
  MASTER_PASSPHRASE: {{ b64enc .Values.sdsDrbd.internal.masterPassphrase }}
{{- end }}
